subat14/kullanici_islemleri/urls.py
from xml.dom.minidom import Document
from django.conf import settings
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views


app_name="user"

urlpatterns = [
path("giris/",views.giris_islemleri,name="Giris"),
path("kayit/",views.kayit,name="kayit"),
path("cikis/",views.cikis,name="cikis"),
] 

subat14/subat14/urls.py
from django.contrib import admin
from django.urls import path,include
from anasayfa.views import *
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),

    path ("",index,name="index"),
    path("selam/<int:id>",dinamik,name="dina"),
    path("urun/<int:id>",dinamik_urun,name="dina_urun"),
    path("ornek/",ornek,name="ornek"),
    path("urungoster/",urun_goster,name="urun_goster"),
    path("tekurun/<int:id>",urun_tek_goster,name="urun_tek_goster"),
    path("user/",include("kullanici_islemleri.urls")),
    #path("ilksayfa",ilksayfa,name="ilksayfa_name")

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

subat14/anasayfa/models.py
from django.db import models

# Create your models here.

class ogr(models.Model):
    isim_soyad=models.CharField(max_length=50)

class ogr2(models.Model):
    isim_soyad=models.CharField(max_length=50)
    aciklama=models.TextField(max_length=50)
    resim=models.FileField(upload_to='kisiresmi/',blank=True,null=True,verbose_name="Kişi resmi ekleyin")
    def __str__(self):
        return self.isim_soyad

class ogr3(models.Model):
    isim_soyad=models.CharField(max_length=50)
    aciklama=models.TextField(max_length=50)
    resim=models.FileField(upload_to='kisiresmi/',blank=True,null=True,verbose_name="Kişi resmi ekleyin")
    def __str__(self):
        return self.isim_soyad
class Urun(models.Model):
    #id=models.AutoField(primary_key=True,verbose_name="Ürün Kodu")
    urun_adi=models.CharField(max_length=50,verbose_name="Ürün Adı")
    urun_fiyat=models.FloatField()
    kategori=models.CharField(max_length=20,verbose_name="Kategori")
    detay=models.TextField(verbose_name="Ürün Açıklaması")
    resim=models.FileField(upload_to='img/',blank=True,null=True,verbose_name="Ürün resmi ekleyin")

    def __str__(self):
        return self.urun_adi

class Urunler2(models.Model):
    urun_adi=models.CharField(max_length=50)
    urun_fiyat=models.FloatField()
    kategori=models.CharField(max_length=20,verbose_name="Kategori")
    detay=models.TextField(verbose_name="Ürün Açıklaması")
    def __str__(self):
        return self.urun_adi

class Urunler3(models.Model):
    urun_adi=models.CharField(max_length=50)
    #urun_fiyat=models.FloatField()
    kategori=models.CharField(max_length=20,verbose_name="Kategori")
    detay=models.TextField(verbose_name="Ürün Açıklaması")
    def __str__(self):
        return self.urun_adi

subat14/kullanici_islemleri/models.py
from django.db import models

# Create your models here.

subat14/kullanici_islemleri/forms.py
from django import forms
from django.forms import widgets
class LoginForm(forms.Form):
    username = forms.CharField(label = "Kullanıcı Adı" , widget=forms.TextInput(attrs={'placeholder': 'Kullanıcı Adı', 'class': 'form-control'}))
    password = forms.CharField(label = "Parola",widget = forms.PasswordInput(attrs={'placeholder': 'Parola', 'class': 'form-control'}))
class RegisterForm(forms.Form):
    username = forms.CharField(max_length = 50,label = "Kullanıcı Adı")
    email = forms.EmailField(max_length=100,label = "Email")
    password = forms.CharField(max_length=20,label = "Parola",widget = forms.PasswordInput)
    confirm = forms.CharField(max_length=20,label ="Parolayı Doğrula",widget = forms.PasswordInput)
    def clean(self):
        username = self.cleaned_data.get("username")
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        confirm = self.cleaned_data.get("confirm")
        if password and confirm and password != confirm:
            raise forms.ValidationError("Parolalar Eşleşmiyor")
        values = {
            "username" : username,
            "password" : password,
            "email"  : email
        }
        return values

subat14/anasayfa/views.py
from django.conf import settings
from django.shortcuts import render,HttpResponse,redirect
from time import *
from .models import *
from subat14 import settings
#import time
# Create your views here.
"""
def index(request):
    return render(request,"ilksayfa.html")

def ilksayfa(request):
    #return render(request,"ilksayfa.html")
    sleep(5)
    return render(request,"ilksayfa2.html")
    #return HttpResponse("Django template 1")
"""
"""def index(request):
    data=ogr2.objects.all()
    sozluk={"ogrenci":data}
    return render (request,"font.html",sozluk)"""

def dinamik(request,id):  #dinamik url
    data=ogr2.objects.filter(id=id)
    sozluk={"og":data}
    return render (request,"font.html",sozluk)

def dinamik_urun(request,id):  #dinamik url
    data=Urun.objects.filter(id=id)
    urun_sayisi=Urun.objects.count()
    
    sozluk={"urunler":data,"urun_sayisi":urun_sayisi}
    #data=ogr2.objects.filter(id=id)
    #sozluk={"og":data}
    return render (request,"urundetay.html",sozluk)
    return render (request,"urundetay.html",sozluk)

"""def unionkayit(request):
    data=ogr2.objects.all().union(ogr3.objects.all())
    sozluk={"union":data}
    return render(request,"font.html",sozluk)

def ornek(request):
    return render(request,"ornek.html")
"""
def index(request):
    urunler=Urun.objects.all()
    sozluk={"urunler":urunler}
    return render(request,"index.html",sozluk)

def ornek(request):
    #base_dir=settings.BASE_DIR
    #sozluk={'base_dir':base_dir}
    #return render(request,"selam.html",sozluk)
    return render(request,"selam.html")

def urun_goster(request):
    urun_goster=Urun.objects.all()
    return render (request,"urun_goster.html",{"urun_goster":urun_goster})

def urun_tek_goster(request,id):
    tek_urun=Urun.objects.filter(id=id)
    urunler=Urun.objects.all()
    return render(request,"tek_urun.html",{"tek_urun":tek_urun,"urunler":urunler})

subat14/kullanici_islemleri/views.py
from django.shortcuts import render,HttpResponse,redirect
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth import login,authenticate,logout
from .forms import *

# Create your views here.

def giris_islemleri(request):
    form = LoginForm(request.POST or None)
    context = {
        "form":form
    }
    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")

        user = authenticate(username = username,password = password)

        if user is None:
            #messages.info(request,"Kullanıcı Adı veya Parola Hatalı")
            return render(request,"login.html",context)

        #messages.success(request,"Başarıyla Giriş Yaptınız")
        login(request,user)
        return redirect("index")
    return render(request,"login.html",context)

    #return HttpResponse("Giris")
def kayit(request):
    form = RegisterForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")
        email = form.cleaned_data.get("email")
        newUser = User(username =username,email=email)
        newUser.set_password(password)
        newUser.save()
        login(request,newUser)
        #messages.info(request,"Başarıyla Kayıt Oldunuz...")
        return redirect("index")
    context = {
            "form" : form
        }
    return render(request,"register.html",context)

def cikis(request):
    logout(request)
    return redirect("index")

   

subat14/anasayfa/templates/content.html
{% load static%}
<!-- HOME -->
<div id="home">
    <!-- container -->
    <div class="container">
        <!-- home wrap -->
        <div class="home-wrap">
            <!-- home slick -->
            <div id="home-slick">
                <!-- banner -->
                <div class="banner banner-1">
                    <img src="{% static './img/banner01.jpg' %}" alt="">
                    <div class="banner-caption text-center">
                        <h1>Bags sale</h1>
                        <h3 class="white-color font-weak">Up to 50% Discount</h3>
                        <button class="primary-btn">Shop Now</button>
                    </div>
                </div>
                <!-- /banner -->

                <!-- banner -->
                <div class="banner banner-1">
                    <img src="{% static './img/banner02.jpg' %}" alt="">
                    <div class="banner-caption">
                        <h1 class="primary-color">HOT DEAL<br><span class="white-color font-weak">Up to 50% OFF</span></h1>
                        <button class="primary-btn">Shop Now</button>
                    </div>
                </div>
                <!-- /banner -->

                <!-- banner -->
                <div class="banner banner-1">
                    <img src="{% static './img/banner03.jpg' %}" alt="">
                    <div class="banner-caption">
                        <h1 class="white-color">New Product <span>Collection</span></h1>
                        <button class="primary-btn">Shop Now</button>
                    </div>
                </div>
                <!-- /banner -->
            </div>
            <!-- /home slick -->
        </div>
        <!-- /home wrap -->
    </div>
    <!-- /container -->
</div>
<!-- /HOME -->

subat14/anasayfa/templates/font.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>İlk Django</title>
</head>
<body>
{% for i in ogrenci %} <!--dinamik url-->
    <a href="/selam/{{i.id}}"><p>{{i.id}} = {{i.isim_soyad}}</p></a>

{% endfor %}

{% for i in og %}
    <a href="/"><p>{{i.id}} = {{i.isim_soyad}}</p></a>
    <p>{{i.aciklama}}</p>
    {% if i.resim %}
        <img src="{{i.resim.url}}" alt="">
    {% else %}
        <p>Resim Yok</p>
    {% endif %}
    
{% endfor %}
</body>
</html>

subat14/anasayfa/templates/header.html
{% load static%}

<header>
    <!-- top Header -->
    <div id="top-header">
        <div class="container">
            <div class="pull-left">
                <span>Welcome to E-shop!</span>
            </div>
            <div class="pull-right">
                <ul class="header-top-links">
                    <li><a href="#">Store</a></li>
                    <li><a href="#">Newsletter</a></li>
                    <li><a href="#">FAQ</a></li>
                    <li class="dropdown default-dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" aria-expanded="true">ENG <i class="fa fa-caret-down"></i></a>
                        <ul class="custom-menu">
                            <li><a href="#">English (ENG)</a></li>
                            <li><a href="#">Russian (Ru)</a></li>
                            <li><a href="#">French (FR)</a></li>
                            <li><a href="#">Spanish (Es)</a></li>
                        </ul>
                    </li>
                    <li class="dropdown default-dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" aria-expanded="true">USD <i class="fa fa-caret-down"></i></a>
                        <ul class="custom-menu">
                            <li><a href="#">USD ($)</a></li>
                            <li><a href="#">EUR (€)</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <!-- /top Header -->

    <!-- header -->
    <div id="header">
        <div class="container">
            <div class="pull-left">
                <!-- Logo -->
                <div class="header-logo">
                    <a class="logo" href="#">
                        <img src="{% static 'img/logo.png' %}" alt="">
                    </a>
                </div>
                <!-- /Logo -->

                <!-- Search -->
                <div class="header-search">
                    <form>
                        <input class="input search-input" type="text" placeholder="Enter your keyword">
                        <select class="input search-categories">
                            <option value="0">All Categories</option>
                            <option value="1">Category 01</option>
                            <option value="1">Category 02</option>
                        </select>
                        <button class="search-btn"><i class="fa fa-search"></i></button>
                    </form>
                </div>
                <!-- /Search -->
            </div>
            <div class="pull-right">
                <ul class="header-btns">
                    <!-- Account -->
<li class="header-account dropdown default-dropdown">
                        <div class="dropdown-toggle" role="button" data-toggle="dropdown" aria-expanded="true">
                            <div class="header-btns-icon">
                                <i class="fa fa-user-o"></i>
                            </div>
                            <strong class="text-uppercase">Hesabım <i class="fa fa-caret-down"></i></strong>
                        </div>
                        {% if request.user.is_authenticated %}
                        <strong class="text-uppercase">{{request.user}} <i class="fa fa-caret-down"></i></strong>
                        <a href="{% url 'user:cikis' %}" class="text-uppercase">Çıkış</a> 
                        {% else %}
                        <a href="/user/giris/" class="text-uppercase">Giriş</a> / <a href="{% url 'user:kayit' %}" class="text-uppercase">Kayıt</a>
                        {% endif %}
                    </li>

                    <!-- /Account -->

                    <!-- Cart -->
                    <li class="header-cart dropdown default-dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" aria-expanded="true">
                            <div class="header-btns-icon">
                                <i class="fa fa-shopping-cart"></i>
                                <span class="qty">3</span>
                            </div>
                            <strong class="text-uppercase">My Cart:</strong>
                            <br>
                            <span>35.20$</span>
                        </a>
                        <div class="custom-menu">
                            <div id="shopping-cart">
                                <div class="shopping-cart-list">
                                    <div class="product product-widget">
                                        <div class="product-thumb">
                                            <img src="./img/thumb-product01.jpg" alt="">
                                        </div>
                                        <div class="product-body">
                                            <h3 class="product-price">$32.50 <span class="qty">x3</span></h3>
                                            <h2 class="product-name"><a href="#">Product Name Goes Here</a></h2>
                                        </div>
                                        <button class="cancel-btn"><i class="fa fa-trash"></i></button>
                                    </div>
                                    <div class="product product-widget">
                                        <div class="product-thumb">
                                            <img src="./img/thumb-product01.jpg" alt="">
                                        </div>
                                        <div class="product-body">
                                            <h3 class="product-price">$32.50 <span class="qty">x3</span></h3>
                                            <h2 class="product-name"><a href="#">Product Name Goes Here</a></h2>
                                        </div>
                                        <button class="cancel-btn"><i class="fa fa-trash"></i></button>
                                    </div>
                                </div>
                                <div class="shopping-cart-btns">
                                    <button class="main-btn">View Cart</button>
                                    <button class="primary-btn">Checkout <i class="fa fa-arrow-circle-right"></i></button>
                                </div>
                            </div>
                        </div>
                    </li>
                    <!-- /Cart -->

                    <!-- Mobile nav toggle-->
                    <li class="nav-toggle">
                        <button class="nav-toggle-btn main-btn icon-btn"><i class="fa fa-bars"></i></button>
                    </li>
                    <!-- / Mobile nav toggle -->
                </ul>
            </div>
        </div>
        <!-- header -->
    </div>
    <!-- container -->
</header>

subat14/anasayfa/templates/homebase.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

	

	<!-- Google font -->
	<link href="https://fonts.googleapis.com/css?family=Hind:400,700" rel="stylesheet">

	<!-- Bootstrap -->
	<link type="text/css" rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />

	<!-- Slick -->
	<link type="text/css" rel="stylesheet" href="{% static 'css/slick.css' %}" />
	<link type="text/css" rel="stylesheet" href="{% static 'css/slick-theme.css' %}" />

	<!-- nouislider -->
	<link type="text/css" rel="stylesheet" href="{% static 'css/nouislider.min.css' %}" />

	<!-- Font Awesome Icon -->
	<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">

	<!-- Custom stlylesheet -->
	<link type="text/css" rel="stylesheet" href="{% static 'css/style.css' %}" />

	<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
		  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
		  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->
	{% block head %}
	<title>E-SHOP HTML Template</title>
	{% endblock head %}
</head>

<body>
	{% block header %}
		{% include "header.html" %}
	{% endblock header %}
		
	{% block slider %}

	{% endblock slider %}
	
	{% block content %}

	{% endblock content %}
	
	{% block sidebar %}

	{% endblock sidebar %}
	<!-- section -->
	
	{% block footer %}
		{%include "footer.html" %}
	{% endblock footer %}
	<!-- FOOTER -->

	<!-- /FOOTER -->

	<!-- jQuery Plugins -->
	<script src="{% static 'js/jquery.min.js' %}"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<script src="{% static 'js/slick.min.js' %}"></script>
	<script src="{% static 'js/nouislider.min.js' %}"></script>
	<script src="{% static 'js/jquery.zoom.min.js' %}"></script>
	<script src="{% static 'js/main.js' %}"></script>

</body>

</html>

subat14/anasayfa/templates/ilksayfa.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <p style="width: 200px;background-color: yellow;">BARIŞ UYAR 1</p>
</body>
</html>

subat14/anasayfa/templates/ilksayfa2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <p style="width: 200px;background-color: red;">BARIŞ UYAR 1</p>
</body>
</html>

subat14/anasayfa/templates/login.html
{% extends "homebase.html" %}
{% block head %}
<title>E-Shop Login</title>
{% endblock head %}
{% block slider %}
<div class="hero-image" id="full-width">
    <div class="hero-text-form">
        <form class="text-center"  method="POST">
            <h3>Lütfen Giriş Yapınız</h3>
            {% csrf_token %}
            <div class="form-floating mb-3">
                {{ form}}
            </div>
            

            <br />
            
            <button type="submit" class="btn btn-lg btn-success">
                Giriş Yap
            </button>
        </form>
    </div>
</div>
<!--**hero image-->
	{% endblock slider %}

subat14/anasayfa/templates/ornek.html
{% extends "index.html" %}

{% block footer %}
<h4>FOOTER</h4>
{% endblock footer %}

{% block header %}
<h4>HEADER</h4>
{% endblock header %}

{% block head %}
<title>ORNEK</title>
{% endblock head %}

subat14/anasayfa/templates/register.html
{% extends "homebase.html" %}
{% block head %}
<title>E-Shop Login</title>
{% endblock head %}
{% block slider %}
<div class="hero-image" id="full-width">
    <div class="hero-text-form">
        <form class="text-center"  method="POST">
            <h3>Lütfen Giriş Yapınız</h3>
            {% csrf_token %}
            <div class="form-floating mb-3">
                {{ form}}
            </div>
            

            <br />
            
            <button type="submit" class="btn btn-lg btn-success">
                Üye Ol
            </button>
        </form>
    </div>
</div>
<!--**hero image-->
	{% endblock slider %}

subat14/anasayfa/templates/selam.html
{% extends "homebase.html" %}

{% block header %}
<h1>BURASI HEADER BLOCKU SELAM.HTML den çalıştırıyor</h1>
{% endblock header %}<h1>BURASI HEADER BLOCKU SELAM.HTML den çalıştırıyor</h1>

subat14/anasayfa/templates/urundetay.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <b>Toplam Ürün Sayısı: {{urun_sayisi}}</b>
    {% for i in urunler %} <!--dinamik url-->
    <p>Ürün ID: {{i.id}}</p>
    <p>Ürün Adı: {{i.urun_adi}}</p>
    <p>Fiyatı: {{i.urun_fiyat}} TL</p>
    <p>Urun Kategorisi: {{i.kategori}}</p>
    <p>Detay: {{i.detay}}</p>

        {% if i.resim %}
        <img src="{{i.resim.url}}" alt="" >
    {% else %}
        <p>Resim Yok</p>
    {% endif %}

{% endfor %}
</body>
</html>